import os
from functools import lru_cache

import regex
import torch
from fastapi import FastAPI, HTTPException, APIRouter
from pydantic import BaseModel, Field
from transformers import AutoModelForCausalLM, AutoTokenizer


app = FastAPI(
    title="SuperAI LLM API",
    description=(
        "REST API for running local LLM inference with a HuggingFace causal language model.\n\n"
        "## Endpoints\n"
        "- **Root** – sanity check\n"
        "- **Health** – device / readiness status\n"
        "- **Infer** – text generation from a prompt\n\n"
        "Interactive docs: `/api/docs` (Swagger UI) · `/api/redoc` (ReDoc)"
    ),
    version="1.0.0",
    contact={"name": "SuperAI Team"},
    license_info={"name": "MIT"},
    docs_url="/api/docs",
    redoc_url="/api/redoc",
    openapi_url="/api/openapi.json",
)

MODEL_DIR = os.environ.get("MODEL_DIR", "/content/model")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Pattern สำหรับลบ special token ที่หลุดมาในรูปแบบ <|extra_NNNN|>
# ปรับเป็น r"<\|[^|>]*\|>" ถ้าต้องการลบ <|...|> ทุกแบบ
EXTRA_TOKEN_RE = regex.compile(r"<\|extra_\d+\|>")


@lru_cache(maxsize=1)
def load_model():
    """Load tokenizer + model from safetensors weights in MODEL_DIR (cached)."""
    tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_DIR,
        use_safetensors=True,  # force loading weights from .safetensors
        torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
        device_map="auto" if DEVICE == "cuda" else None,
        low_cpu_mem_usage=True,
    )
    if DEVICE == "cpu":
        model = model.to(DEVICE)
    model.eval()
    return tokenizer, model


class InferRequest(BaseModel):
    prompt: str = Field(..., description="Input text prompt sent to the model.")
    max_new_tokens: int = Field(
        256, ge=1, le=4096,
        description="Maximum number of new tokens to generate (1–4096).",
    )
    temperature: float = Field(
        0.7, ge=0.0, le=2.0,
        description="Sampling temperature. Lower = more deterministic, higher = more creative (0.0–2.0).",
    )
    top_p: float = Field(
        0.95, ge=0.0, le=1.0,
        description="Nucleus sampling probability mass. Only tokens whose cumulative probability ≤ top_p are considered (0.0–1.0).",
    )
    do_sample: bool = Field(
        True,
        description="Enable stochastic sampling. Set to False for greedy decoding.",
    )

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "prompt": "Explain quantum entanglement in simple terms.",
                    "max_new_tokens": 256,
                    "temperature": 0.7,
                    "top_p": 0.95,
                    "do_sample": True,
                }
            ]
        }
    }


class InferResponse(BaseModel):
    output: str = Field(..., description="Generated text (prompt tokens excluded).")
    prompt_tokens: int = Field(..., description="Number of tokens in the input prompt.")
    completion_tokens: int = Field(..., description="Number of tokens generated by the model.")

router = APIRouter(prefix="/api", tags=["SuperAI LLM"])


@router.get(
    "/",
    summary="Root",
    description="Sanity-check endpoint. Returns a greeting message to confirm the API is running.",
    response_description="Greeting message.",
    responses={200: {"content": {"application/json": {"example": {"message": "Hello from SuperAI FastAPI demo"}}}}},
)
def read_root():
    return {"message": "Hello from SuperAI FastAPI demo"}


@router.get(
    "/health",
    summary="Health check",
    description=(
        "Returns the service readiness status and the compute device currently in use "
        "(`cuda` when a GPU is available, `cpu` otherwise)."
    ),
    response_description="Service status with active device.",
    responses={200: {"content": {"application/json": {"example": {"status": "ok with cuda"}}}}},
)
def health():
    return {"status": f"ok with {DEVICE}, model=${os.environ.get("HF_REPO")}, build_no={os.environ.get("BUILD_VERSION")}"}


@router.post(
    "/infer",
    response_model=InferResponse,
    summary="Run LLM inference",
    description=(
        "Generate text from a prompt using the locally-loaded causal language model.\n\n"
        "**Notes**\n"
        "- The model is loaded lazily on the first request and then cached for subsequent calls.\n"
        "- Only the *newly generated* tokens are returned; the prompt is not echoed back.\n"
        "- Returns `503` if the model directory is missing or the weights cannot be loaded."
    ),
    response_description="Generated text together with prompt and completion token counts.",
    responses={
        200: {
            "content": {
                "application/json": {
                    "example": {
                        "output": "Quantum entanglement is when two particles...",
                        "prompt_tokens": 9,
                        "completion_tokens": 128,
                    }
                }
            }
        },
        503: {"description": "Model unavailable – weights could not be loaded."},
    },
)
def infer(req: InferRequest):
    try:
        tokenizer, model = load_model()
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"Model not available: {exc}")

    inputs = tokenizer(req.prompt, return_tensors="pt").to(model.device)
    prompt_tokens = inputs["input_ids"].shape[-1]

    with torch.no_grad():
        generated = model.generate(
            **inputs,
            max_new_tokens=req.max_new_tokens,
            temperature=req.temperature,
            top_p=req.top_p,
            do_sample=req.do_sample,
            pad_token_id=tokenizer.pad_token_id or tokenizer.eos_token_id,
        )

    # Strip the prompt tokens so we only decode the newly generated text.
    new_tokens = generated[0][prompt_tokens:]
    output = tokenizer.decode(new_tokens, skip_special_tokens=True)

    # ลบ special token ที่ skip_special_tokens ลบไม่ออก (เช่น <|extra_2919|>)
    output = EXTRA_TOKEN_RE.sub("", output).strip()

    return InferResponse(
        output=output,
        prompt_tokens=int(prompt_tokens),
        completion_tokens=int(new_tokens.shape[-1]),
    )

app.include_router(router)
if __name__ == "__main__":
    import uvicorn

    uvicorn.run(
        app,
        host=os.environ.get("HOST", "0.0.0.0"),
        port=int(os.environ.get("PORT", "8000")),
        log_level=os.environ.get("LOG_LEVEL", "info"),
    )
